### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [tony-developer/tony-developer.github.io#2]
### Добрый день!

Отлично:
- Полностью проходит проверку валидация имени
- Полностью проходит проверку номер телефона
- Полностью проходит проверку URL/ip
___

### Надо исправить:

- Не выполнен пункт чеклиста: `Корректно оформлено Readme.md. Проставлена версия, заголовок, ссылка на проект и инструкция по запуску проекта`
- Проходят невалидные почтовые ящики: `ya2@ewq.r` (tld - минимум из двух символов), `ya2@ewq.23` (tld из цифр не может быть)

Можно лучше:
- В репозитории есть лишний файл - `.idea`
---

**Важно:** после исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на *github.io*.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by mrprovoker** [comment]
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*

**Comment by tony-developer** [comment]
Спасибо!
